### ISSUE TITLE
Translation problem - place of worship

### ISSUE THREAD

**Issue by plepe** [plepe/openstreetmap-tag-translations#16]
@Cybereric wrote:

I've a little problem with the translations for "place_of_worship" and "religion"

In French "place_of_worship" belongs to the masculine gender and "religion" belongs to the feminine gender.

I thought I was wrong in my first translation.

So I've translate again with the value for "place_of_worship" in the masculine gender

    "tag:amenity=place_of_worship": "Lieu de culte",
    "tag:amenity=place_of_worship religion!=christian;jewish;muslim;sikh": "Autre que chrétien, juif, musulman ou sikh",
    "tag:amenity=place_of_worship religion=christian": "chrétien",
    "tag:amenity=place_of_worship religion=jewish": "juif",
    "tag:amenity=place_of_worship religion=muslim": "musulman",
    "tag:amenity=place_of_worship religion=sikh": "sikh",

and the value for "religion" with the feminine gender

    "tag:religion": "Religion",
    "tag:religion=buddhist": "boudhiste",
    "tag:religion=christian": "chrétienne",
    "tag:religion=hindu": "hindoue",
    "tag:religion=jewish": "juive",
    "tag:religion=multifaith": "multiconfessionnelle",
    "tag:religion=muslim": "musulmane",

I thought it was good but in fact no it's not good as you see below in the picture

Either I've all the values in feminine, either in masculine
I need the both

And the problem will be the same in Spanish, Italian (cristiano / cristiana), etc...

I hope you'll find a solution. ;-)

Best Regards

Éric

![masculine feminine](https://user-images.githubusercontent.com/249012/41219353-4f00c5bc-6d5e-11e8-9a16-aac2a80f014f.png)

**Comment by plepe** [comment]
Yeah, it's true. The Category `religion` currently uses "translation of 'tag:amenity=place_of_worship': translation of 'tag:religion=christian'". In fact, this should be "translation of 'tag:amenity=place_of_worship religion=christian'" - but then, the translation should be something like "Church" or "Christian Church", not only the translation of religion.

On the other hand, there are places of worship, which are not churches ...

Maybe the translation should be "Place of worship: christian" resp. "Lieu de culte: chrétien"?

**Comment by Cybereric** [comment]
I don't see in the code why it actually doesn't work !
> "tag:amenity=place_of_worship religion=christian": "chrétien"  

Is it for the sidebar ?

>  "tag:religion=christian": "chrétienne",

Is it for the popup ? 

Anyway you saw the problem.
> Maybe the translation should be "Place of worship: christian" resp. "Lieu de culte: chrétien"?

Yes "Place of Worship"  must have a masculine value

**Comment by plepe** [comment]
> >  "tag:amenity=place_of_worship religion=christian": "chrétien"

> Is it for the sidebar ?

Yes, but currently I don't use it. If we use it, it should translate the whole thing (amenity=place_of_worship AND religion=christian).

Also: "tag:amenity=vending_machine vending=cigarettes" (currently not used, but I should) translates to "Zigarettenautomaten" in German resp. "Distributeur de cigarettes" in French - it translates the whole thing.

I could change it right now, but I have to introduce a check - if the string is translated, use "tag:amenity=place_of_worship religion=christian", if not, use "tag:amenity=place_of_worship" and "religion=christian".

Hope to do that in the next few days.

**Comment by plepe** [comment]
Update: Since now the "tag:amenity=vending_machine vending=bicycle_tube" is used in the cycle_amenities category. (It's easier, as there is no fallback to "tag:amenity=vending_machine" "tag:vending=bicycle_tube").

see plepe/openstreetbrowser-categories-main@aee96a7e1136ce2e9f438ba32b30fae669825837

**Comment by plepe** [comment]
So, during the time until I figure out this check, you could create a pull request which translates "tag:amenity=place_of_worship religion=christian" (and other religions) to "Church" or "Christian Place of worship" or something like that.

Also @IgorEliezer for 'pt-br'. Russian also seems to only translate to 'christian', but there's no active translator.

**Comment by plepe** [comment]
Ah, no. Actually it's all wrong.

Because if it's a church or not also depends on the `building=*` tag. So I introduced a (hopefully) better system:

```json
    "tag:building": "Building",
    "tag:building=cathedral": "Cathedral",
    "tag:building=chapel": "Chapel",
    "tag:building=church": "Church",
    "tag:building=church religion=christian": "Church",
    "tag:building=mosque": "Mosque",
    "tag:building=mosque religion=muslim": "Mosque",
    "tag:building=religious": "Religious building",
    "tag:building=shrine": "Shrine",
    "tag:building=synagogue": "Synagogue",
    "tag:building=synagogue religion=jewish": "Synagogue",
    "tag:building=temple": "Temple",
    "tag:building=temple religion=sikh": "Sikh-Temple",
```

It's online right now. Please tell me, what you think of it. (Test it when changing display language to 'English' or 'German').

**Comment by plepe** [comment]
@Cybereric any comments? Otherwise I would close this issue ...
