### ISSUE TITLE
 In the "tag-translations" file

### ISSUE THREAD

**Issue by Cybereric** [plepe/openstreetmap-tag-translations#38]
Some questions :

"tag:building=generic": "",  generic means the same thing as "building=yes" ?

"tag:building=ger": "",  What is it ? Yurt ? => https://en.wikipedia.org/wiki/Yurt

"tag:foot": "",   I understand "foot" but when it's used ?

"tag:horse": "",  Same for "horse"

"tag:service": "", Same, used for what and when ?

"tag:species": "", Is it for trees ?

"tag:residential=HDB": "",  Is it this thing ? => https://en.wikipedia.org/wiki/HDB

**Comment by plepe** [comment]
> "tag:building=generic": "", generic means the same thing as "building=yes" ?

I don't know :-) I just know, that it is being used. I would say yes.

> "tag:building=ger": "", What is it ? Yurt ? => https://en.wikipedia.org/wiki/Yurt

Yes.

> "tag:foot": "", I understand "foot" but when it's used ?

Access restriction on highways. https://wiki.openstreetmap.org/wiki/Key:foot
Very often used as highway=path, bicycle=designated, foot=yes (that more or less equals a cycleway). Example: https://overpass-turbo.eu/s/FJe

highway=path, foot=designated (more or less equals highway=footpath).

> "tag:horse": "", Same for "horse"

Same, yes.

> "tag:service": "", Same, used for what and when ?

Used together with highway=service, railways or waterways: https://wiki.openstreetmap.org/wiki/Key:service

> "tag:species": "", Is it for trees ?

Yes. https://wiki.openstreetmap.org/wiki/Key:species

> "tag:residential=HDB": "", Is it this thing ? => https://en.wikipedia.org/wiki/HDB

Yes. See also plepe/OpenStreetBrowser#79

**Comment by Cybereric** [comment]
I must think how to translate "foot", "horse" and so on
If I just say "pied"(foot) ou "cheval"(horse) it'll mean nothing 
I must find an expression , a good turn of phrase

For residential=HDB  i'll use "Housing and Development Board"
It makes more sense than the abbreviation

**Comment by Cybereric** [comment]
Hello,
It could be great to have the ability to translate the filters.
Here are the **untranslated values** I've found and some errors.

In **Leisure Sport and Shopping**
> **Gastronomy**
>**Filter "Type"**
food_court
ice_cream

> **Filter "Food"**
noodle
wings
casserole
chicken
fish
sub            

_Remarks_
There's a duplicate for "noodle" I think as I have already nouilles (french for noodles)
An with "friture" too 

> **Filter "Dessert"**
bagel 
bougatsa
frozen_yogurt
ginger bread
chimney cake
langos
pastry
petit_four
pies
pogacha
poppy_seed_roll
punchcake
savory_pancakes
teahouse
waffle

> **Filter "Ethnicity"**
american
argentinian
baiana
balkan
bavarian
belarusan 
bolivian
brazilian
cantonese
capixaba
croation
czech
danese
gaucho
german
hawaian
german
hungarian
iranian
jewish
kyo_ryouri
latin_american
lebanese
malagasy
mediteranean
mineria
new-mexican
okinawa_ryori
pakistani
peruvian
polish
portugese
rehenish
russian
shandong
sichuan
texan
westphalian

> **Filter "Diet"**
Objects with diet information

======================

In **Shopping**
> **Filter "Type"**
general
boutique  
dairy
spices
fishing

_Remarks_
For "boutique"  there's already a shop=boutique

=============================

In **Craft**

> **Filter "Type"**
Tailor;   there's an extra ; 

==============================

In **Sports**

> **Filter "Type"**
badminton
american_footbal
billiards
bmx
canadian_football
cockfighting                     
darts
field_hockey
ice_hockey
ice_skating
model_aerodrome
motocross
rugby_leage  
rugby_union
sailing
surfing
weightlifting

_Remark_
It's  in fact "league" and not "leage"

=========================

In **Children amenities**

> **Filter "Type"**
`There's  d&#039;  instead of  '`

=========================

In **Services**
> **Emergency services**
`There's  d&#039;  instead of  '`

> **Health**
blood bank
blood_donation
dentist
hospital                

_Remark_ 
There's already one hospital I think.

> **Communication**
public_relation
audiovisual_production
film_production

> **Offices**
government
company
estate_agent
insurance
lawyer
educational_institution
administrative
telecomunication
ngo
quango
association 
it
accountant
tax_advisor
employment_agency
research
financial
newspaper
political_party
advertising_agency
therapist
travel_agent
publisher

> **Tourism**
tourist_accomodation

===================

In **Culture and religion"

> **Memorials**  _Could you please add the other types like :_
plaque 
blue_plaque
statue
bust
stele
stone
ghost_bike
war_memorial

> **Religion**
> **Filter "Type"**
wayside_chapel

===========================

In **Transportation**
> **Public transportation**
> **Public transport map**
aerialway
bus
ferry
subway
train
tram
trolleybus

===========================

That's all ;-)

**Comment by plepe** [comment]
They are untranslated, but some of them are already translateable:
* Gastronomy, Type: `tag:amenity=food_court`, `tag:amenity=ice_cream`
* Gastronomy, Food and Dessert and Ethnicity: `tag:cuisine=*` (there were some missing strings, I just added them)
* Gastronomy, Diet: Indeed missing, it's now to be found in the categories repository.
* Shopping: `tag:shop=*`. The strings you mentioned were indeed missing (I couldn't find boutique though)
* Craft: The ';' is to be found in the French translation only - you may remove it (seems you added it yourself: fe05ed268d75d4e5cc914a424330e2ae5fcf7d31)
* Sports: `tag:sport=*`. I added the missing strings. Fixed rugby_league.

Will do more later.

**Comment by plepe** [comment]
* `&#039;` - fixed, but not online yet.
* Health: blood_bank and blood_donation had amenity, not healthcare. Fixed. I also merged similar types (e.g. `amenity=doctors` and `healthcare=doctor`; `amenity=hospital` and `healthcare=hospital`) into one type. I added more `healthcare=*` tags to the translation.
* Offices: fixed (translations were not used)

**Comment by plepe** [comment]
* Tourism: there was a typo in the translation file (office=tourist_accomodation). Fixed.
* Religion: added `historic=wayside_chapel` to  the translation.
* PT Map: use translation (fixed).

Memorial needs a bit of work, won't do it now :-)

**Comment by plepe** [comment]
* Memorial: done - that was quite some work (for several reasons: 1st: some use memorial=*, others memorial:type=*; 2nd: memorial/monument confusion; 3rd: it's hard to find icons. [Maybe you can help](https://github.com/plepe/OpenStreetBrowser/blob/master/doc/Icons.md)?). I added some more memorial=* values for translation.

I hope, I didn't miss anything. Next time, please open a new issue.
