### ISSUE TITLE
Memorials

### ISSUE THREAD

**Issue by Cybereric** [plepe/openstreetmap-tag-translations#41]
Hello,

> Next time, please open a new issue.

Done :-)

> Memorial:  done - that was quite some work (for several reasons) 

Sorry for that ;-)

> 1st:  some use memorial=, others memorial:type=; 

- memorial=* is the good value
- memorial_type shouldn't be used, see  =>  https://wiki.openstreetmap.org/wiki/Key:memorial:type

> 2nd:  memorial/monument confusion

Yes both are commemorative things. Some are quite "small" (memorials) and monuments are large.
No size defined but if we take the classic roman triumph arch (between 19 and 20 m high) I think we could say that something bigger than 15/20 m is a monument  (even if it's named memorial of xxx)
To sum up : memorials and monuments are separated in OSM by their size
Actually there are more than 3000 "monuments" in France. I think less than 10% are well tagged as monuments !
I'll try to launch (at least in France) a huge cleaning. Working on.

I think I have clearly specified the wiki pages on memorials and monuments.
- https://wiki.openstreetmap.org/wiki/Tag:historic%3Dmonument
- https://wiki.openstreetmap.org/wiki/Tag:historic%3Dmemorial

So back to OpenStreetBrowser 
I see that monuments are recognized
Perhaps the whole category should be named "**Memorials & monuments**" ?
And another filter  called "**Monuments**" could take place in the list "Title/Type/Conflict/..." .

> 3rd:  it's hard to find icons. Maybe you can help?)

I'll check this and I'll give you my opinion about icons as a whole.

> I added some more memorial=* values for translation.

 Thanks a lot !
I think there are problems with some of these values that are not memorials or should not be used (in **bold** below)

Let's see :

- plaque  => ok
- **plate  => no**
It's deprecated (synonym of plaque)  
See >>> https://wiki.openstreetmap.org/wiki/Tag:memorial%3Dplaque

- blue_plaque  =>  ok
- statue  =>  ok
- war_memorial  =>  ok
- **war_monument  =>  no**  
Only 11 items in Tag Info, "war_memorial" should be used instead.  
As somebody said this tag is problematic as it does not describe a physical object as the others in the category ( a plaque, a stele, ....)

- stolperstein  =>  ok
- stone  =>  ok
- bust  =>  ok
- **person =>  no**    
A person is not a OSM object and not a memorial.
I've take a look on how it's used. There are 250 memorial=person / 48 memorial=public_person used in fact on different things like plaques, statues, etc. Many of them have duplicate info with memorial:type=*
If a monument or a memorial (ex statue) is about a person the tags "subject:wikidata" and "subject:wikipedia" are the good choice to add information
- stele  =>  ok
- obelisk  =>  ok   
Shouldn't be with the stele it's not the same thing.  There's a man made=obelisk too.
- sculpture   
This value is not on the wiki page (528 values in TagInfo) but I think it's interesting because some memorials may have a non-figurative style.
- ghost_bike  =>  ok
- **vehicule/tank   =>  no**     
It's not a memorial.
I don't see why these vehicles are commemorative. If they are historic they should have the tag "historic=yes" or "historic=vehicle", "historic=tank". There's already "locomotive, railway_car, ship, aircraft" values (see the historic objects of the _Historic.place_ map (https://wiki.openstreetmap.org/wiki/Historical_Objects/Map_Properties)
- cross  =>  ok    
But difficult to see if it's well tagged (confusion with "historic=wayside_cross" and "man_made=cross" (more for summit cross))
- **flood_mark / highwater_mark  =>  no**   
They are not memorials.
The correct tag seems to be "historic=flood_mark" or "historic=highwater_mark", it's still in discussion.  Even if floods marks are made to remember something they're more technical objects.  They are not dedicated to a person, an event like usual memorials.
- **grave  =>  no**   
It's not a memorial.  
As far I've seen the 212 Taginfo values should be "historic=tomb"
There's a tag "cemetery=grave" too.
- **graveyard  =>  no**  
It's  not a memorial.  
Among the 162 Taginfo values you can see here (https://overpass-turbo.eu/s/GUp)  in Highgate Cemetery (London) some "historic=tomb" bad tagged (same contributor)
For a graveyard there's a tag "amenity=grave_yard"  It describes the small cemetery (typically from Middle Ages) surrounding a worship place.  See => https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dgrave_yard

> I hope, I didn't miss anything. 

No good work ;-)

**Comment by plepe** [comment]
> * memorial=* is the good value
> * memorial_type shouldn't be used, see  =>  https://wiki.openstreetmap.org/wiki/Key:memorial:type

That's right. I'm planning to add a warning of `memorial:type` or `memorial_type` is used.

> So back to OpenStreetBrowser
> I see that monuments are recognized
> Perhaps the whole category should be named "**Memorials & monuments**" ?

Done in `en` and `de`.

> And another filter called "**Monuments**" could take place in the list "Title/Type/Conflict/..." .

Done. (Called "monument | memorial" - maybe not optimal. Didn't want to add another string).

## Values
Thanks for the feedback on the values.
I left the synonyms in the queries (e.g. 'plate'), but they are no longer shown in info and filter.

> * obelisk  =>  ok
>   Shouldn't be with the stele it's not the same thing.  There's a man made=obelisk too.

It's now a separate filter.

> * **vehicule/tank   =>  no**
>   It's not a memorial.
>   I don't see why these vehicles are commemorative. If they are historic they should have the tag "historic=yes" or "historic=vehicle", "historic=tank". There's already "locomotive, railway_car, ship, aircraft" values (see the historic objects of the _Historic.place_ map (https://wiki.openstreetmap.org/wiki/Historical_Objects/Map_Properties)

If a ghost_bike is a memorial, why can't a vehicle also be a memorial. Of course it's something different than a war relic, it has to be something which has been erected to remember something (which in the most cases might be wrong).

What's for example with this: https://yadi.sk/i/jHWZqurb3Vwq6H

Of course it could be historic=vehicle, but the way it is arranged looks very commemorative to me ... I wouldn't say this is not a memorial ...

> * **flood_mark / highwater_mark  =>  no**

You are right. I added this to the "historic" category. I now assume historic=flood_mark for all variants. Also, I added a few translations (flood_mark=*, flood_date).
