### ISSUE TITLE
Translation error "Carpenter“

### ISSUE THREAD

**Issue by robhubi** [plepe/openstreetmap-tag-translations#46]
In OSM craft=carpenter means  „Zimmermann/Zimmerer”, not “Tischler“ in German
See https://wiki.openstreetmap.org/wiki/DE:Tag:craft%3Dcarpenter

**Comment by plepe** [comment]
Deine Änderung 7a86c93398b3db495112dea4af0471a8f9e6169c ist ja schon lange online.

Danke!
